# Generated by Django 4.2.16 on 2026-07-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('css_selector', models.CharField(blank=True, help_text="Optional CSS selector to watch only part of the page, e.g. '#content'. Leave blank to watch the whole page.", max_length=200)),
                ('check_frequency_minutes', models.PositiveIntegerField(choices=[(15, 'Every 15 minutes'), (60, 'Every hour'), (360, 'Every 6 hours'), (1440, 'Once a day')], default=60)),
                ('last_hash', models.CharField(blank=True, max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('old_hash', models.CharField(blank=True, max_length=64)),
                ('new_hash', models.CharField(max_length=64)),
                ('notified', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='monitor.watchedsite')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
